config/routes.rb
Ncvocals::Application.routes.draw do
  
  root to: "home_pages#index"

  match '/help',      to: 'home_pages#help'
  match '/about',     to: 'home_pages#about'
  match '/contact',   to: 'home_pages#contact'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def index
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "NC Vocals"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/home_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>
<p>
  NC Vocals Directory is currently a listing of the Contemporary A cappella group in the central North Carolina region.
</p>
<p>
	We are currently only adding groups that fall under the style "Contemporary A Cappella" but hope to one day include vocal groups of other styles.  If you are a member of a contemporary A Cappella group in NC and are not in this directory, please send an email to feldmannst@gmail.com and we will be happy to add you!
</p>

app/views/home_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the webmaster at feldmannst@gmai.com with any questions about NC Vocals.</a>.
</p>

app/views/home_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  To view all Groups currently listed in our system, click on "Groups" in the top navigation bar, or <%= link_to "click here", "#" %>.

  If you have any other questions, please contact Scott at feldmannst@gmail.com!
</p>

app/views/home_pages/index.html.erb
<div class="center hero-unit">
	<h1>Welcome to NC Vocals!</h1>

	<h2>
		This is the home page for the NC Vocal Directory, a listing of all contemporary a cappella groups in the central North Carolina region
	</h2>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright 2013 - Scott Feldmann
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "NC VOCALS", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Groups", '#' %></li>
          <li><%= link_to "Events", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
  		<%= yield %>
  		<%= render 'layouts/footer' %>
  	</div>
  </body>
</html>